src/main/groovy/com/cedarsoftware/util/Visualizer.groovy
Add source scope to getScopeRelativeToSourceMethod in Visualizer.groovy. Also, remove code that did a substring on source field rpm type to get the scope key. This is no longer needed since we have renamed epm classes from coverage.Coverage to Coverage (etc.).
=> Add source scope to visualizer groovy code. See comment for details.

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/webapp/js/visualize.js
1.	Create new VisualizerRelnfo class that holds info about a source and target cube and their relationship. Use new class in Visualizer instead of a map. 
2.	Pass in VisualizerRelnfo to the  processCube method and its sub-methods, rather than relying on as member variable.
3.	Create new Visualizerlnfo class that holds info about scope, groups, levels, nodes and edges. Use new class in Visualizer instead of maps. 
4.	Remove usage of .toArray.
5.	Create variable for value.lastIndexOf in getDotSuffix method.
=> Visualizer changes based on comments made on PR 246

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy
DevOps requested a way to see the active n-cube count for a given ApplicationID, which will allow them to automate the verification of an n-cube release.
I decided to piggyback off of search and default cubeNamePattern, content and active to make the call easier for them, but also allow for a more robust search count if necessary.
=> Added getSearchCount that returns the number of results found by search

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerHelper.groovy
Changes:
1.	Changed Visualizer to retrieve only a minimal set of traits for each class.
2.	Removed class traits from title in Visualizer.
3.	Eliminated dependency on pd:busType trait in Visualizer (the Visualizer now only relies on traits recognized by Dynamis).
Tested by comparing json for the VisInfo object returned by Visualizer before and after changes. 
The server side performance for loading the Visualizer for the large WorkersCompensationProduct has improved by 33% as a result.
=> Change Visualizer to retrieve only a minimal set of traits

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy
1. Changed ALL_GROUPS_MAP.keySet() to be a static constant.
2. Replaced one last occurrence of columns.find with axis.findColumn.
3. Added load of available scope values for scope keys from both EPM cubes and from ENT_APP. This will be made available to UI so that the scope picker can have dropdowns with values. For now, it’s used to display available scope values to users when they get toasts about missing scope. Some of the new code will be refactored to be moved to n-cube (TODO).
4. Moved messy GString messages into their own methods for readability.
5. Extracted local variable for source field trait map.
6. Changed label line length multiplier to be declared as double.
=> Added load of available scope value for scope keys + other minor fixes

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerConstants.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/webapp/js/visualize.js
1. Fixed bug introduced with recent round of improvements that caused errors when using a non-EPM class as the starting point for a visualization.
2. Changed error message when using anything but an rpm.class as the starting point for a visualization.
3. Increase the default levels shown in the visualizer from 2 to 3.
=> Visualizer: Allow non-EPM class as starting point for visualization

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerHelper.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/webapp/css/visualize.css, src/main/webapp/html/visualize.html, src/main/webapp/js/visualize.js
1. Add ability to load entire graph with all traits.
2. Add ability to load an individual node with all traits.
3. Visualizer is no longer extending NCubeGroovyController.
4. Better formatting of list of available scope values in toast messages.
5. Better formatting of lists in right-side info pane of visualizer.
6. For non-EPM classes where no scope is missing, load up the visualizer without the initial scope prompt.
7. Move methods from Visualizer to VisualizerInfo and VisualizerRelInfo.
8. Add constructors for VisualizerInfo and VisualizerRelInfo.
=> Visualizer: Add ability to load traits and other assorted improvements

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/webapp/js/visualize.js
1. Scope is now saved off to local storage and available when re-opening the cube for visualization or using the back button to navigate back to a visualization.
2. Fixed issues with the scope picker. It is now displaying already picked scope keys and is able to add scope keys.
TODO: The key in the scope picker is case sensitive, which doesn’t play well with the case insensitive scope that comes across from the server (Product vs. product, etc.).
TODO: When a key is picked in the scope picker, make the value a drop-down populated with available scope values.
3. Added temporary code to handle cube names with "_" instead of "." (e.g. rpm_class_product instead of rpm.class.product) in nce.getSelectedCubeName()after a page refresh (not always, but often).
TODO: Figure out what the deal is …
=> Visualizer: Changes to handling of scope in js

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/webapp/html/visualize.html, src/main/webapp/js/visualize.js
1. Renamed trimNetworkData method in visualizer.js to setGroupsAndExcluded. Also simplified the method a great deal. The lists of nodes and edges passed in to the visjs network is now the same as what the server returns (no new lists created, should help memory). The nodes and edges that we don’t want to include in the network (given the selected level and/or group) are instead removed from the network directly. This allows a huge graph to render faster (though still slow, with most of the time spent rendering the nodes in the browser after visualizer.js finishes up its processing; something to look into).
It also fixes a bug in the old trimNetworkData code that caused groups to be included in some cases even when not checked.
It is now possible to render the highest level for the WC …
=> Visualizer: Optimize trim of network data in js

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerConstants.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/webapp/js/visualize.js
1.	Removed class name and dash line from node labels.
2.	Changed hover text for nodes to indicate class and scoped name (e.g. “Product – WorkersCompensationProduct”).
3.	Changed hover text for edges to indicate valid values for field on class (e.g. “Valid values for field Places on Risk”).
4.	Increased font size of field names in graph to make them more prominent. The field names actually make up for the information lost since they indicate the class of the target node (e.g. field name Places pointing to USAddress of type Place). 
5.	Removed rpm.class and rpm.enum prefixes from the displayed class names on nodes, in info panel and on error messages.
=> Visualizer - change labels and remove class name prefixes

src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/webapp/css/visualize.css, src/main/webapp/html/visualize.html, src/main/webapp/js/visualize.js
1.	Fix bug that caused null pointer when loading traits on enums.
2.	Change group buttons to pick up the color specified for their corresponding network shapes.
3.	Make network physics parms available for display. To get them to display, put a breakpoint in the Chrome console after “_networkPhysicsParms.hide();”, then execute “_networkPhysicsParms.show();” in the console.
=> Visualizer: Change group buttons to pick up graph colors + make network physics parms available

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerConstants.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/webapp/js/visualize.js
1.	Added validation that cube starts with rpm.class (removed same edit from NCubeController). Also validating that start cube has at least a field and a trait axis. This is in fact the minimum require by Dynamis to load a cube as an rpm.class.
2.	Changed info panel title to show class type and scope name for EPM classes (e.g. Product WorkersCompensationProduct). For non-EPM classes it shows the full cube name minus rpm.class or minus rpm.enum (e.g. account.CustomerSecurityAgreement).
3.	Changed link to cube in info panel to say “Open n-cube”.
=> Visualizer: Added start cube validation and changed info panel

src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/webapp/css/visualize.css, src/main/webapp/html/visualize.html, src/main/webapp/js/constants.js, src/main/webapp/js/visualize.js
1.	Display all network options in Einstein section, not just physics options.
2.	Network option defaults loaded from Vis rather than hard coded.
3.	Load Einstein section dynamically. Removed hard coded html tags.
4.	Highlighting changes values in yellow in Einstein section.
5.	Changed network physics parm minVelocity from 0.75 to 0.85. This helps settle large networks down much faster (thanks, John!).
6.	Changed network parms to add shadows to edges and nodes. 
7.	Removed clustering feature that included overrides of Vis code. It is not working correctly (possibly since upgrading to using DataSets and new version of Vis). The feature is really not of much value now that groups can be turned on/off, levels changed and the info panel allows to navigate to a new visual. This also eliminates …
=> Visualizer: Display all network options for edit dynamically, change minVelocity parm, remove clustering feature and more

src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy
Changed wording on title for enums to use scoped name of source, if one is available. For example, from "Valid values for field RateFactors on Coverage" to "Valid values for field RateFactors on StopGapCoverage".
=> Visualizer: Changed wording on title for enums to use scoped name of source

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/webapp/html/visualize.html, src/main/webapp/js/index.js, src/main/webapp/js/visualize.js
1.	Rework how visualizer clears notes upon load from server. The way implemented a few days ago had issues:  One issue was that it would clear all prior notes, even those not pertaining to the visualizer (for example, a note about cubes updated from HEAD). Another issue was that a visualizer note with missing scope info would not always display when it should.
2.	Updated network physics parms for minVelocity, gravitationalConstant and springConstant.
3. Right align text in Einstein section
=> Visualizer: Rework how visualizer clears notes upon load from server. Update physics parms.

src/main/webapp/css/visualize.css, src/main/webapp/html/visualize.html, src/main/webapp/js/visualize.js
1.	Remove the scope picker button. It isn’t working currently because the map in the scope picker is case sensitive, which doesn’t play well with the case insensitive scope that comes across from the server (Product vs. product, etc.). Also, the scope picker is no longer needed for required scope since we provide prompts for that in toasts. The user could use the scope picker for optional scope, but the plan is to provide that functionality similar to the prompts for missing required scope. 
2.	Add tooltip with full scope on scope hover.
=> Visualizer: Remove scope picker. Add tooltip with full scope on scope hover.

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerConstants.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/webapp/css/visualize.css, src/main/webapp/html/visualize.html, src/main/webapp/js/constants.js, src/main/webapp/js/visualize.js
NOTE!!!! The cube Visualizer.TypesToAdd in UD.REF.APP bheekin2 must be committed along with the merge of this PR. John, email or text me (I'll send my cell phone number separately) when you are ready so I can commit the cube, or you can go ahead and do it yourself.
1.	Added link for “Add to xxxx” in info panel. Displays dropdown of types that can be added to the class in question. For now, displays message that the add functionality is not yet implemented. The options in the dropdown are driven by a new cube Visualizer.TypesToAdd. This cube needs to be committed along with the merge of this PR.
2.	Removed level info from info panel.
3.	Removed scoped name from info panel.
4.	Split out info panel title into two titles. EPM classes uses both titles (title 1 is class name minus the rpm.class …
=> Visualizer: Add link in info panel for adding types to class (risks, coverages, limits, etc.)

src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/webapp/html/visualize.html, src/main/webapp/js/visualize.js
1.	Changed centralGravity network parm from 0.3 to 3.
2.	Added functionality to load the graph with basic, “fast” options first, then when stabilized, load with full options. In this process, also make sure to honor any tweaks the user might have done to the network settings. The difference between basic options and full options is as follows: 
a.	nodes.shadow.enabled: false vs. true
b.	edges.shadow.enabled: false vs. true 
c.	edges.arrows.to.enabled: false. vs. true
d.	edges.arrowStrikethrough: false vs. true
3.	General fine-tuning of how/when network data and network options are updated, when the network is destroyed and when a reload is executed.
4.	Fixed bug that caused incorrect nodes to show when doing “New visual from here” from and to the same cube.
5.	Refactored network options …
=> Visualizer: Load graph with basic options first, then load with full options + misc. other fixes

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerConstants.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/resources/config/VisualizerConfig.json, src/main/resources/config/VisualizerTypesToAdd.json, src/main/webapp/js/constants.js, src/main/webapp/js/visualize.js
This is the reworked PR based on code review feedback + with some additional changes. 
1.	Created a new VisualizerConfig json file in NCE that holds configs for the visualizer. Configurations are only loaded first time through or if the app id changes. 
2.	Moved the TypesToAdd cube from UD.REF.APP to a json file in NCE. Also moved typesToAdd method in Visualizer.groovy into VisualizerInfo.groovy.
3.	Refactored to pass the VisualizerInfo object back and forth between the .js and the .groovy. Previously, the object was only passed down to the .js and had to be recreated in .groovy.
4.	No longer passing selectedGroups and selectedLevel back and forth from server from js. Not necessary.
5.	Commented out code relating to gathering availableScopeKeys. Not needed currently, but I will revisit …
=> Visualizer: Create VisualizerConfig json file + other changes

pom.xml, src/main/groovy/com/cedarsoftware/util/RpmVisualizer.groovy, src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerConstants.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/resources/config/VisualizerConfig.json, src/main/webapp/js/constants.js, src/main/webapp/js/visualize.js
*** NOTE! *** The outstanding PR to n-cube for getReferencedCubeNames must be merged prior to merging this PR.
1. Changed to use 3.4.123-SNAPSHOT of NCube that contains the refactored NCube.getReferencedCubeNames method.
2. Changed visualizer code to use coordinate information for non-rpm cubes.
3. Improve formatting of top node for both rpm and non-rpm visuals. Move configs for this to VisualizerConfig.json.
=> Visualizer: Improve formatting of top node for both rpm and non-rpm visuals

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizer.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerConstants.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerRelInfo.groovy, src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerConstants.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/resources/config/VisualizerConfig.json, src/main/webapp/css/visualize.css, src/main/webapp/html/visualize.html, src/main/webapp/js/visualize.js
1.	Refactored groovy classes and js to support loading of cell values for non-rpm cubes.  
2.	Click “Show cell values” in info panel on an non-rpm cube and you now see coordinates loaded with cell values. The default is to not execute command cells, but the user can click the coordinate link and have the cell be executed (or click execute all). The “CubeWithLotsOfDifferentValues” in bheekin2 is a good example.
3.	The loading and executing of cells seems to be working mostly OK by now, but I have an “under construction” message up for the Show Value section for non-rpm cubes since it still needs plenty more work. 
4.	Will work on exception handling and coordinate display next, among other things. 
5.	Hoping for lots of feedback on this PR! So many possibilities.
=> Visualizer: First pass at values mode for non-rpm cubes

src/main/groovy/com/cedarsoftware/util/RpmVisualizer.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerRelInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerConstants.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/resources/config/VisualizerConfig.NetworkOverrides.json, src/main/resources/config/VisualizerConfig.json, src/main/webapp/css/visualize.css
1.	Change link color for cell values to standard blue color.
2.	Change max level for non-rpm cubes to default to 999999. Rpm cubes stay at default of 3 levels.
3.	Reduced size of arrows in graph. I think we had this config at some point, but I deleted it by mistake?
4.	Increased size of node shadows for non-rpm cubes slightly from 10 to 12. This makes them a little bigger, but the color also blurs and makes the shadow less prominent.
5.	Broke out the VisualizerConfig.json into to json to make it easier to edit. Lots of further improvement could be made in cube design here, but not high priority.
6.	Removed obsolete sort of target scope map for non-rpm.
7.	Change RpmVisualizer to return same type as super class where it wasn’t already.
=> Visualizer: Misc. small fixes

src/main/groovy/com/cedarsoftware/util/VisualizerCellInfo.groovy, src/main/webapp/css/visualize.css, src/main/webapp/js/visualize.js
1. Fix bug in doing find on node with multiple hits. Links in toast were not working.
2. Only apply word wrapping on pre tags in info panel for non-rpm cell values.
=> Visualizer: Fix bug in "find node" with multiple hits

src/main/webapp/js/index.js
Reverts jdereg/n-cube-editor#417
=> Revert "Expression link would not properly open cube contained in tab overflow."
