src/main/webapp/css/ncube.css, src/main/webapp/html/ntwobe.html, src/main/webapp/js/ntwobe.js
=> Updates for HOT ncube tab.

src/main/webapp/css/ncube.css, src/main/webapp/html/ntwobe.html, src/main/webapp/index.html, src/main/webapp/js/constants.js, src/main/webapp/js/ntwobe.js
Removed coordinates scroll bar - can now drag left/right.  
Added cell edit modal to HOT.
Fixed misc display issues.
=> Added cell edit to HOT.

src/main/webapp/js/ntwobe.js
non-string meaning stored as an integer (e.g. 2 vs "2").
=> HOT display fixes for non-string (stored) and date range set row headers.

src/main/webapp/js/ntwobe.js
added - disable hide columns link on menu if 1 column or less
=> [RA-22314] Hide column functionality

src/main/webapp/css/ncube.css, src/main/webapp/html/ntwobe.html, src/main/webapp/js/constants.js, src/main/webapp/js/ntwobe.js
@jdereg you should see a better search than what we had the other day.  Still need to figure out how to get coordinates of all results, especially those not yet rendered, more on that tomorrow.  For now, I wanted you to check out what's there.
=> HOT introduce search, limited functionality but shows results in table.

src/main/groovy/com/cedarsoftware/service/ncube/NCubeService.groovy
if it already exists (active or deleted)
=> [RA-23608] Error message on create n-cube 

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/webapp/css/index.css, src/main/webapp/js/constants.js, src/main/webapp/js/index.js
Not sure why beans.xml is showing up in here...
=> Heartbeat marks tabs

src/main/webapp/css/ncube.css, src/main/webapp/html/ntwobe.html, src/main/webapp/js/constants.js, src/main/webapp/js/ntwobe.js
Column widths should autosize.
Row heights are not autosized. The height is determined by the new lines in the cell.
=> [RA-23651] Bound autosizing on vertical and horizontal

src/main/webapp/css/ncube.css, src/main/webapp/js/ntwobe.js
Also includes freezing horizontal axis button.
=> HOT search - Fix for 1-D cubes.

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/webapp/css/index.css, src/main/webapp/js/index.js
See commit desc for change list.
=> Tym Changes

src/main/webapp/css/index.css, src/main/webapp/index.html, src/main/webapp/js/index.js
I left delete on the cube list menu, which allows selection of multiple cubes from the branch.  Delete from the tab menu only deletes the selected tab.
=> Change delete modal and delete multiple / single.

src/main/webapp/index.html, src/main/webapp/js/index.js
=> Filter delete cube options based on cube search.

src/main/webapp/js/index.js, src/main/webapp/js/ntwobe.js
Still issue with back button going back twice, but fixes hot issues.
=> history and hot fixes.

src/main/webapp/js/index.js
=> Change app/ver/status/branch if cube changed as a result of removing tab

src/main/webapp/js/details.js, src/main/webapp/js/index.js, src/main/webapp/js/ncube.js, src/main/webapp/js/ntwobe.js
json view uses a third-party plugin that's a little more complicated; still trying to get that one to work.
=> Open tabs save position of view (not json view)

src/main/webapp/html/ntwobe.html, src/main/webapp/index.html, src/main/webapp/js/index.js, src/main/webapp/js/ntwobe.js
Not sure how that extra if got there.
=> Add Filtering for Modals

src/main/webapp/js/common.js, src/main/webapp/js/index.js, src/main/webapp/js/ntwobe.js
=> Tab loading performance issue.

src/main/webapp/css/ncube.css, src/main/webapp/js/index.js, src/main/webapp/js/ntwobe.js
Tested with Mark and Kerry connected to my local and this change works for them.
=> Might be fix for some users' search buttons disappearing.

src/main/webapp/js/common.js, src/main/webapp/js/ntwobe.js
I didn't mean to leave that commit message, it was pre-filled by intellij
=> Fix Kerry's search issue.

src/main/webapp/css/index.css, src/main/webapp/js/common.js, src/main/webapp/js/constants.js, src/main/webapp/js/index.js, src/main/webapp/js/ntwobe.js, src/main/webapp/js/prop-builder.js
I've made some tweaks which I believe are working in the right direction, but I haven't been able to completely eliminate the issues at hand. Since I will be out tomorrow, I hoped this might make it a little better for users.
=> Attempt to clean up memory / DOM leaks

src/main/webapp/css/index.css, src/main/webapp/js/common.js, src/main/webapp/js/constants.js, src/main/webapp/js/index.js, src/main/webapp/js/ntwobe.js, src/main/webapp/js/prop-builder.js
Reverts jdereg/n-cube-editor#216
=> Revert "Attempt to clean up memory / DOM leaks"

src/main/webapp/html/ntwobe.html, src/main/webapp/js/ntwobe.js
=> Allow change axis during hide columns.

src/main/groovy/com/cedarsoftware/service/ncube/NCubeService.groovy
Remove wild card handling from NCubeService.search (moved into n-cube NCubeManager.search).
=> Remove wild card handling from NCubeService.search

pom.xml, src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerHelper.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/webapp/js/constants.js, src/main/webapp/js/visualize.js
Changes to the Visualizer:
1. Updated VisualizerHelper to run with code corresponding to Dynamis 5.2.0 (includes loading traits only for fields that are r:exists = true and handling of effective version, among other things). TODO: Get rid of VisualizerHelper by adding in Dynamis via Grapes.  Will need a new Dynamis API that allows us to load only select traits. 
2. Improved prompts to the user as to what minimal scope is required to start a visualization based on which class is to be visualized.
3. Updated Visualizer to handle missing scope beyond the minimally required start scope. If there is missing scope for a class, the node for the class  appears in the visualization and the node provides information about the issue when selected (previously, the visualization would blow up with an …
=> Visualizer changes

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerHelper.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy
**NOTE!!! Don't merge until the following pull request for n-cube has been merged: https://github.com/jdereg/n-cube/pull/225**
Visualizer changes: 
1. Improved handling of exceptions occurring during load of classes due to missing scope (requires new release of NCube, PR is pending)
2. Added default values to initial minimum scope.
3. Improved handling and messages for missing minimum scope.
=> Visualizer improved handling of initial scope and exceptions

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy
Changed .compareTo to > and <.
Extracted code relating to building the node label into a separate method for readability.
Removed TODO’s about .lowerCase in getScopeRelativeToSource() and getDefaultScope(). Need to convert to lower case since the scope in both cases is displayed to the user.
=> A few more cleanup items for the Visualizer

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerHelper.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/webapp/js/visualize.js
1. Back to declaring new maps used for scope as CaseInsensitiveMap.
2. Introduced retained scope from Dynamis 5.0.
3. Changed how node.id, edge.from and edge.to are determined.
4. Remove display of “required scope all referenced cubes” and “optional scope all referenced cubes” in node titles. Instead, display retained scope and scope that is available to load the class.
5. Added check for missing declared required scope.
6. Move methods that aren’t original Dynamis methods (except for slight modifications) from VisualizerHelper to Visualizer.
7. Fixed issue in vis.js with null scope or invalid scope.
8. Updated default optional scope.
=> Introduce retained scope and assorted other fixes/improvements

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy
1. Removed right hand angle brackets.
2. Added type back to variables declared by ->in closures.
3. Refactored how VisualizerRelInfo group name is handled.
4. Added comment to getRequiredAndOptionalScopeKeys method in VisualizerRelInfo.
=> Assorted Visualizer cleanup based on PR feedback.

src/main/webapp/js/ntwobe.js
=> Squashing bugs.

src/main/groovy/com/cedarsoftware/util/Visualizer.groovy
Fixed bug introduced with last Visualizer PR.  "Show traits" was just showing minimal traits, not all traits.
=> Fixed bug introduced with last Visualizer PR. 

src/main/webapp/html/visualize.html, src/main/webapp/js/common.js, src/main/webapp/js/constants.js, src/main/webapp/js/details.js, src/main/webapp/js/index.js, src/main/webapp/js/ncube.js, src/main/webapp/js/ntwobe.js, src/main/webapp/js/visualize.js
1.	Removed Load button from the Visualizer.
2.	Added setInterval function for scope field in visualizer.js. Reloads from server 3000 ms after last key press. Reloads immediately if field loses focus.
3.	Removed temporary override in visualizer.js of saveOrDeleteValue function. Changed the function in common.js to work with both objects and primitives.
4.	Changed ‘object’ into a constant in all places it’s used in NCE java script.
=> Visualizer: Remove Load button

src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/webapp/css/visualize.css, src/main/webapp/html/visualize.html, src/main/webapp/js/visualize.js
1. Change group check boxes to bootstrap buttons.
2. Remove space above title in info panel.
3. Change title in info panel for enums.
=> Visualizer: Change group check boxes to bootstrap buttons and change title in info panel

src/main/groovy/com/cedarsoftware/util/VisualizerConstants.groovy, src/main/webapp/css/visualize.css, src/main/webapp/js/index.js, src/main/webapp/js/visualize.js
Change new clearAllErrors function to use Gritter's API method removeAll. Also, allow user to double click missing scope key in scope input text.
=> Visualizer: Change clearAllErrors function to use Gritter's API method removeAll.

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizer.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerConstants.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerHelper.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerRelInfo.groovy, src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerConstants.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/resources/config/VisualizerConfig.json, src/main/webapp/html/visualize.html
1.	Created new RpmVisualizer.groovy class that extends Visualizer.groovy. Ditto for  RpmVisualizerInfo.groovy and RpmVisualizerRelInfo.groovy.
2.	Changed NCubeController to direct to Visualizer for non-rpm cubes and to RpmVisualizer for rpm class cubes. This code can be refactored when we move the visualizer out to a separate project.
3.	Rpm class cubes: the visualization works as before. 
4.	Non-rpm cubes: the visualization will display the top level node only for now. Added toast that this is under construction.
=> Visualizer: First pass at non-rpm visualizations

src/main/groovy/com/cedarsoftware/util/RpmVisualizer.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerHelper.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerRelInfo.groovy, src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerCellInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerHelper.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy
Reverts jdereg/n-cube-editor#351
=> Revert "Visualizer: Minor clean-up items"

src/main/groovy/com/cedarsoftware/util/RpmVisualizer.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerRelInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerConstants.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/main/resources/config/VisualizerConfig.NetworkOverrides.json, src/main/resources/config/VisualizerConfig.json, src/main/webapp/css/visualize.css
Reverts jdereg/n-cube-editor#355
=> Revert "Revert "Visualizer: Misc. small fixes""

src/main/groovy/com/cedarsoftware/util/RpmVisualizer.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerHelper.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerRelInfo.groovy, src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerCellInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerHelper.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy
Reverts jdereg/n-cube-editor#352
=> Revert "Revert "Visualizer: Minor clean-up items""

src/main/groovy/com/cedarsoftware/util/RpmVisualizer.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerRelInfo.groovy, src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerRelInfo.groovy, src/test/groovy/com/cedarsoftware/util/RpmVisualizerTest.groovy, src/test/groovy/com/cedarsoftware/util/VisualizerTest.groovy, src/test/resources/rpmvisualizer/rpm.class.Coverage.json, src/test/resources/rpmvisualizer/rpm.scope.class.Coverage.traits.json, src/test/resources/visualizer/CubeWithExecutedCellsWithURLs.json
Improved test coverage. There are 11 visualizer groovy classes. 8 of them are at 100%, 2 at 98% and one at 68%. The last one at 68% is RpmVisualizerHelper, which contains code copied from Dynamis. This class will go away when we refactor how we interact with Dynamis.
=> Improved test coverage

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/webapp/js/constants.js, src/main/webapp/js/index.js, src/main/webapp/js/ntwobe.js
I call this a "temp fix" bc it will go away once we get the PR framework in place. But for right now, since we stop people at commit instead of update, we needed a good way to communicate ahead of time that they can't commit their own changes for certain cubes.
=> Temp fix for permissions when unable to commit.

pom.xml, src/main/groovy/com/cedarsoftware/util/RpmVisualizer.groovy, src/main/groovy/com/cedarsoftware/util/RpmVisualizerRelInfo.groovy, src/main/groovy/com/cedarsoftware/util/Visualizer.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerHelper.groovy, src/main/groovy/com/cedarsoftware/util/VisualizerInfo.groovy, src/main/resources/config/VisualizerConfig.NetworkOverrides.json, src/test/groovy/com/cedarsoftware/util/RpmVisualizerTest.groovy
1. Display prompt for optional scope applying to entire graph in toast (previously only in info panel for individual nodes, now in both).
2. Turn shadows off for network.
=> Visualizer: Display prompt for optional scope applying to entire graph in toast

src/main/webapp/css/index.css, src/main/webapp/index.html, src/main/webapp/js/index.js
=> Multiple changes

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/webapp/js/index.js
Reverts jdereg/n-cube-editor#416
=> Revert "Enable "Clear Server Cache" for all users except when branch is HEAD"

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/webapp/js/index.js
Reverts jdereg/n-cube-editor#415
=> Revert "Middle click should close cube tab."

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/groovy/com/cedarsoftware/service/ncube/NCubeService.groovy
Reverts jdereg/n-cube-editor#414
=> Revert "Allow impersonation admin tool in NCE."

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/webapp/js/constants.js, src/main/webapp/js/index.js
@jdereg Made the change we discussed.
=> Multiple changes.

src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/webapp/css/index.css, src/main/webapp/index.html, src/main/webapp/js/common.js, src/main/webapp/js/constants.js, src/main/webapp/js/index.js, src/main/webapp/js/jquery.gritter.js
@jdereg Commit requests work, as well as the links. However, for right now, the requests are only viewable on the modal, and clicking them reveals the cube list they are committing. More functionality to follow, but this gets us in the door and able to start using them.
=> Preliminary commit request changes; bug fixes.

pom.xml, src/main/groovy/com/cedarsoftware/controller/NCubeController.groovy, src/main/webapp/index.html, src/main/webapp/js/index.js
@jdereg For when you release 3.6.11.
=> Add compare to view commits.

src/main/webapp/js/form-builder.js, src/main/webapp/js/index.js
=> Form builder section bug.

src/main/resources/static/css/index.css, src/main/resources/static/index.html, src/main/resources/static/js/constants.js, src/main/resources/static/js/index.js, src/main/resources/static/js/test.js
=> run all tests

src/main/resources/static/js/index.js
Tied to https://github.com/jdereg/n-cube/pull/321
***Only merge after consuming ncube 4.0.8
=> Make check permissions for multiple actions one server call

src/main/resources/static/js/form-builder.js, src/main/resources/static/js/nce-builder-options.js, src/main/resources/static/js/ncubeJsonEditor.js, src/main/resources/static/js/ntwobe.js
=> Add default, sorted, and fireAll to addAxis

src/main/resources/static/css/form-builder.css, src/main/resources/static/js/form-builder.js, src/main/resources/static/js/nce-builder-options.js
=> Fix form-builder table header positioning.

src/main/resources/static/js/index.js, src/main/resources/static/js/ntwobe.js
Fixes for:
-Edited cubes would not populate in modified cubes list while filtered.
-Using search reset button would clear out newly editted cubes within modified cubes list.
=> Fix for Modified Cubes list during filtering

src/main/resources/static/js/index.js
=> Permissions check js error fix.

src/main/resources/static/js/index.js
Fixed bug while editing cube from different app than currently selected.
=> Fix for Modified Cubes list - bug fix

changelog.md, src/main/resources/static/js/index.js, src/main/resources/static/js/nce-builder-options.js
=> Added support to see revision history for cubes currently in a deleted state.

changelog.md, src/main/resources/static/js/ntwobe.js
=> Made cell value text selected when moving cells while editing.

changelog.md, src/main/resources/static/css/form-builder.css, src/main/resources/static/js/constants.js, src/main/resources/static/js/form-builder.js, src/main/resources/static/js/index.js, src/main/resources/static/js/nce-builder-options.js, src/main/resources/static/js/ntwobe.js
And other code cleanup since I was ripping the js apart.
=> Switched NCube view filtering to utilize NCube.hyperMapReduce.
